### ISSUE TITLE
Pipeline adaptation

### ISSUE THREAD

**Issue by r-xue** [r-xue/auto_selfcal#1]
### To-Do List:

- [x] The workflow sequence and helper functions should be modularized so they can be easily used by Pipeline.
- [x] Fix the codestyle issue to avoid future problems.
- [x] Use Python/CASA logging for statements.
- [ ] use the standard package/module file structure.
- [ ] Ideally, the new restructured code can be used either in the Pipeline environment or as a "script" for the monolithic CASA:
  - To minimize the change to the original code, we could design a translating/adaptive layer to deal with externally developed scripts/modules in general. They are often/unfortunately written for the monolithic CASA (i.e. with the extra bits provided by `casashell`), rather than standard pythonic modules/class/functions. Under the proposed layer, the same namespace could present a "true" CASA task (when running as a script in CASA) or a Pipeline wrapper of a CASA task (when running as an "extern" dependency of Pipeline). Then external codes can be used in both contexts, without substantial rewriting.

### Check List:

- [ ] The refactored code should still work similarly to the original code in the "CASA script" mode.

**Comment by r-xue** [comment]
A new branch (`pipeline-adaptation-more`) is created from 292bb78baeda331e306f470b5989626c0d4e6330 (the latest commit to `pipeline-adaptation-with-code-refactoring`).
